### ISSUE TITLE
supportedrates configuration is ignored and advertising beacons are invalid

### ISSUE THREAD

**Issue by nm-mrt** [travelping/freewtp#3]
Whatever I put into the config `application->radio->supportedrates` the supported rates sent out in advertising beacons is always `6(B), 9(B), 12(B), 18(B), 24, 36, 48, 54` which is incorrect for 2.4GHz Wi-Fi. It should be something like `1(B), 2(B), 5.5(B), 11(B)`. At the moment a client not supporting 6, 9, 12, and 18 (802.11g) should not be able to connect to our access point. 

Also there is an extended support rates list sent out with a single entry which is invalid (0x7f is no valid baud rate).

![beacon](https://cloud.githubusercontent.com/assets/18024215/19183489/dfe880ba-8c78-11e6-9c08-04a885feb422.png)

**Comment by RoadRunnr** [comment]
Supported rates from the configuration is overruled by the AC in the Add WLAN settings.

6(B), 9(B), 12(B), 18(B), 24, 36, 48, 54 is 802.11g only (no 802.11b support). As far as I understand the specs, doing that is valid.

802.11g specifies 6, 9, 12 and 18 MBit as basic rates and that is what the AC sets. This should exclude any 802.11b only client from connecting and is done on purpose by the AC.

The 0x7f in Extended Rates is also set by the AC and seems to be AC bug or configuration problem.

**Comment by RoadRunnr** [comment]
0x7f (127) in Extended Rates is a valid setting (but wireshark doesn't know that).

802.11-2012, Sect. 8.4.2.3 defines the supported rates element and the special meaning of 127:

> Support for the mandatory features of Clause 20 is required in order
> to join the BSS that was the source of the Supported Rates element or
> Extended Supported Rates element containing this value.
