### ISSUE TITLE
capwap_daemon

### ISSUE THREAD

**Issue by ghost** [travelping/freewtp#7]
This function can be replaced with the Linux system function daemon.

int daemon(int nochdir, int noclose);

**Comment by RoadRunnr** [comment]
Could you please be more specific. Which function can be replaced?

Besides, daemon(3) is a libc function, not a Linux system function.

**Comment by ghost** [comment]
void capwap_daemon(void);

**Comment by RoadRunnr** [comment]
You are right. I consider a micro cleanup. The current version might be redundant, but it is not wrong or broken.

Anyhow, you are welcome to submit a pull request to replace it.
