### ISSUE TITLE
AC

### ISSUE THREAD

**Issue by ghost** [travelping/freewtp#9]
Why not continue to develop the AC  belong to  smartcapwap?

**Comment by RoadRunnr** [comment]
The final goal is to have clustered AC. For that, Erlang is in our opinion better suited.

**Comment by ghost** [comment]
Can you write a description of how to run AC(Erlang )?

**Comment by RoadRunnr** [comment]
first, from project. That issue belong to the https://github.com/travelping/ergw-capwap-node project.

second, very valid point. Unfortunately, the CAPWAP project is severely lacking in documentation and right now no one really has time to change that.

**Comment by RoadRunnr** [comment]
see https://github.com/travelping/ergw-capwap-node/issues/3
